FROM alpine:3.20
RUN apk add --no-cache ca-certificates tzdata && addgroup -S dns && adduser -S -G dns dns
COPY --chmod=755 bin/linux/apid /usr/local/bin/apid
USER dns
EXPOSE 8080/tcp 8443/tcp
ENTRYPOINT ["apid", "-env", "/app/.env"]
